#!/bin/bash

# ClearPolicy Waitlist - Environment Setup Helper
# This script creates your .env.local file with Supabase credentials

echo "🔧 ClearPolicy Waitlist - Environment Setup"
echo "============================================"
echo ""
echo "Your Supabase Project URL: https://ltauqjonpcjjdvbvupae.supabase.co"
echo ""
echo "Please go to Supabase Dashboard → Settings → API to get your keys."
echo "URL: https://supabase.com/dashboard/project/ltauqjonpcjjdvbvupae/settings/api"
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists. Creating .env.local.new instead."
    OUTPUT_FILE=".env.local.new"
else
    OUTPUT_FILE=".env.local"
fi

echo "Enter your Supabase anon/public key (starts with 'eyJ'):"
read ANON_KEY

echo ""
echo "Enter your Supabase service_role key (starts with 'eyJ'):"
read SERVICE_KEY

echo ""
echo "Enter your Resend API key (optional, press Enter to skip):"
read RESEND_KEY

# Create the .env.local file
cat > "$OUTPUT_FILE" << EOF
# Supabase Configuration - Auto-generated by setup-env.sh
# Project: ClearPolicy Waitlist

# Project URL
VITE_SUPABASE_URL=https://ltauqjonpcjjdvbvupae.supabase.co
SUPABASE_URL=https://ltauqjonpcjjdvbvupae.supabase.co

# Anon/Public Key (used in frontend)
VITE_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}

# Service Role Key (KEEP SECRET - used in backend/scripts)
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}

# Resend API Key (for confirmation emails)
RESEND_API_KEY=${RESEND_KEY:-your_resend_key_here}
EOF

echo ""
echo "✅ Created $OUTPUT_FILE with your credentials!"
echo ""
echo "Next steps:"
echo "  1. Run the SQL migration in Supabase (copy from supabase/migrations/)"
echo "  2. Export your data from Lovable Cloud as CSV"
echo "  3. Run: npm run import-waitlist lovable_waitlist_export.csv"
echo ""

